export enum RESPONSE_STATUS {
  GENERAL = 'GENERAL',
  DUPLICATE = 'DUPLICATE',
  NOT_FOUND = 'NOT_FOUND',
  CREDENTIALS = 'CREDENTIALS',
  FIELDS_VALIDATION = 'FIELDS_VALIDATION',
  JWT = 'JWT',
  TOKEN = 'TOKEN',
  BAD_DATA = 'BAD_DATA',
  NOT_EXIST = 'NOT_EXIST'
}
